apiVersion: v1
appVersion: 0.9.1
version: 0.4.1
description: A Helm chart for JFrog Pipelines
home: https://jfrog.com/pipelines/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/pipelines/icon/pipelines-logo.png
keywords:
- pipelines
- jfrog
- devops
maintainers:
- email: rimasm@jfrog.com
  name: rimusz
- email: daniele@jfrog.com
  name: danielezer
- email: eldada@jfrog.com
  name: eldada
name: pipelines
sources:
- https://bintray.com/beta/#/jfrog/pipelines
- https://github.com/jfrog/charts/pipelines
dependencies:
- name: postgresql
  version: 6.3.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: redis
  version: 9.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: rabbitmq
  version: 6.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
