dependencies:
- name: postgresql
  version: 6.3.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: redis
  version: 9.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: rabbitmq
  version: 6.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
